### ISSUE TITLE
Failed to fix host object open.

### ISSUE THREAD

**Issue by Uplinkpro** [deafdudecomputers/PalWorldSaveTools#29]
Trying to use your tool and i get to the point where I change the GUID's and this is the output: 

`PalWorldTools Version: 0.9.7
Enter new GUID: B71E8005000000000000000000000000
Enter old GUID: 00000000000000000000000000000001
WARNING: Running this script WILL change your save files... Backup recommended.
Press enter to continue...
Converting LocalWorldSave\Level.sav to JSON
Decompressing sav file
Loading GVAS file
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Program Files\Python312\Lib\multiprocessing\spawn.py", line 122, in spawn_main
    exitcode = _main(fd, parent_sentinel)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python312\Lib\multiprocessing\spawn.py", line 131, in _main
    prepare(preparation_data)
  File "C:\Program Files\Python312\Lib\multiprocessing\spawn.py", line 246, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "C:\Program Files\Python312\Lib\multiprocessing\spawn.py", line 297, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen runpy>", line 286, in run_path
  File "<frozen runpy>", line 98, in _run_module_code
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\Uplin\Downloads\PalWorldSaveTools.v0.9.7\fix_host_save.py", line 1, in <module>
    from fix_save import *
  File "C:\Users\Uplin\Downloads\PalWorldSaveTools.v0.9.7\fix_save.py", line 23, in <module>
    os.remove(file)
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'fix_save.log'
Converting LocalWorldSave\Players\00000000000000000000000000000001.sav to JSON
Decompressing sav file
Loading GVAS file
Modifying JSON save data...
Converting data to SAV, saving to LocalWorldSave\Level.sav
Compressing SAV file
Compressing: 0% completedERROR: Unpack failed: incomplete input
Press any key to continue . . .`

**Comment by deafdudecomputers** [comment]
Yeah, I realized my mistake. I've just pushed a new release. Please check on [here](https://github.com/deafdudecomputers/PalWorldSaveTools/releasesl). Thank you.
