### ISSUE TITLE
Fix Host Save Not working

### ISSUE THREAD

**Issue by Maickeenn** [deafdudecomputers/PalWorldSaveTools#33]
I got this error while running your script:
```
Process MPMapPropertyProcess-1:
Traceback (most recent call last):
  File "C:\Python312\Lib\multiprocessing\process.py", line 314, in _bootstrap
    self.run()
  File "C:\Users\Gabriel\PalwordTest\Repos\PalWorldSaveTools\internal_libs\palobject.py", line 647, in run
    setproctitle(f"{self.__class__.__name__}:{self.path}")
```
Seems that it doesnt work with 0.4.11

**Comment by deafdudecomputers** [comment]
Send the save here. It should work on saves that we're updated on/after feybreak patch.
